"""Plugin-specific error codes for API responses."""

from enum import StrEnum


class PluginErrorCode(StrEnum):
    """Error codes for plugin operations.

    Code ranges:
    - 2000-2099: Registration errors
    - 2100-2199: Installation errors
    - 2200-2299: Configuration errors
    - 2300-2399: Health errors
    - 2400-2499: Compatibility errors
    """

    # Not found errors
    PLUGIN_NOT_FOUND = "PLUGIN_NOT_FOUND"
    PLUGIN_NOT_IN_REGISTRY = "PLUGIN_NOT_IN_REGISTRY"

    # Registration conflicts
    PLUGIN_ID_CONFLICT = "PLUGIN_ID_CONFLICT"
    PLUGIN_CLASS_CONFLICT = "PLUGIN_CLASS_CONFLICT"

    # Contract violations
    PLUGIN_MISSING_DEFINITION = "PLUGIN_MISSING_DEFINITION"
    PLUGIN_CONTRACT_INVALID = "PLUGIN_CONTRACT_INVALID"
    PLUGIN_METADATA_MISSING = "PLUGIN_METADATA_MISSING"

    # Installation errors
    PLUGIN_INSTALL_FAILED = "PLUGIN_INSTALL_FAILED"
    PLUGIN_UNINSTALL_FAILED = "PLUGIN_UNINSTALL_FAILED"
    PLUGIN_NO_INSTALL_COMMAND = "PLUGIN_NO_INSTALL_COMMAND"
    PLUGIN_VERSION_INVALID = "PLUGIN_VERSION_INVALID"
    PLUGIN_ALREADY_INSTALLED = "PLUGIN_ALREADY_INSTALLED"

    # Configuration errors
    PLUGIN_CONFIG_INVALID = "PLUGIN_CONFIG_INVALID"
    PLUGIN_CONFIG_TYPE_ERROR = "PLUGIN_CONFIG_TYPE_ERROR"
    PLUGIN_CONFIG_REQUIRED_MISSING = "PLUGIN_CONFIG_REQUIRED_MISSING"
    PLUGIN_CONFIG_ENUM_INVALID = "PLUGIN_CONFIG_ENUM_INVALID"
    PLUGIN_CONFIG_CONSTRAINT_VIOLATED = "PLUGIN_CONFIG_CONSTRAINT_VIOLATED"

    # Health errors
    PLUGIN_HEALTH_CHECK_FAILED = "PLUGIN_HEALTH_CHECK_FAILED"
    PLUGIN_HEALTH_CHECK_TIMEOUT = "PLUGIN_HEALTH_CHECK_TIMEOUT"
    PLUGIN_HEALTH_CHECK_NOT_IMPLEMENTED = "PLUGIN_HEALTH_CHECK_NOT_IMPLEMENTED"

    # Compatibility errors
    PLUGIN_INCOMPATIBLE_VERSION = "PLUGIN_INCOMPATIBLE_VERSION"
    PLUGIN_DEPENDENCY_MISSING = "PLUGIN_DEPENDENCY_MISSING"
