# shared/metrics/__init__.py
"""
Metrics module for Prometheus monitoring.
Exports all metrics and helper functions.
"""

from .prometheus import (
    Counter,
    Gauge,
    Histogram,
    MetricsCollector,
    TimingContext,
    chunking_duration,
    chunks_created,
    cpu_utilization,
    embedding_batch_duration,
    embeddings_generated,
    extraction_duration,
    files_failed,
    files_processed,
    gpu_memory_total,
    gpu_memory_used,
    gpu_utilization,
    ingestion_duration,
    operation_duration,
    operations_completed,
    operations_created,
    operations_failed,
    memory_total,
    memory_used,
    memory_utilization,
    metrics_collector,
    processing_lag,
    qdrant_points,
    qdrant_upload_errors,
    queue_length,
    record_chunks_created,
    record_embeddings_generated,
    record_file_failed,
    record_file_processed,
    record_operation_completed,
    record_operation_failed,
    record_operation_started,
    registry,
    start_metrics_server,
    system_info,
    update_processing_lag,
    update_queue_length,
)

__all__ = [
    # Classes
    "MetricsCollector",
    "TimingContext",
    # Metrics
    "system_info",
    "operations_created",
    "operations_completed",
    "operations_failed",
    "operation_duration",
    "files_processed",
    "files_failed",
    "chunks_created",
    "embeddings_generated",
    "queue_length",
    "processing_lag",
    "extraction_duration",
    "chunking_duration",
    "embedding_batch_duration",
    "ingestion_duration",
    "gpu_memory_used",
    "gpu_memory_total",
    "gpu_utilization",
    "cpu_utilization",
    "memory_utilization",
    "memory_used",
    "memory_total",
    "qdrant_points",
    "qdrant_upload_errors",
    # Collector instance
    "metrics_collector",
    # Helper functions
    "record_operation_started",
    "record_operation_completed",
    "record_operation_failed",
    "record_file_processed",
    "record_file_failed",
    "record_chunks_created",
    "record_embeddings_generated",
    "update_queue_length",
    "update_processing_lag",
    "start_metrics_server",
    # Registry
    "registry",
    # From prometheus_client (for compatibility)
    "Counter",
    "Gauge",
    "Histogram",
]
