name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    
    - name: Check code formatting with Black
      run: |
        poetry run black --check .
    
    - name: Lint with Ruff
      run: |
        poetry run ruff check .
      env:
        QDRANT_HOST: localhost
        JWT_SECRET_KEY: test-secret-key
    
    - name: Type check with Mypy
      run: |
        poetry run mypy vecpipe webui
      env:
        QDRANT_HOST: localhost
        JWT_SECRET_KEY: test-secret-key

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    
    services:
      qdrant:
        image: qdrant/qdrant:latest
        ports:
          - 6333:6333

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    
    - name: Wait for Qdrant to be ready
      run: |
        for i in {1..30}; do
          if curl -f http://localhost:6333/health 2>/dev/null; then
            echo "Qdrant is ready!"
            break
          fi
          echo "Waiting for Qdrant... ($i/30)"
          sleep 2
        done
    
    - name: Run tests with pytest
      run: |
        poetry run pytest --cov=vecpipe --cov=webui --cov-report=xml
      env:
        QDRANT_HOST: localhost
        QDRANT_PORT: 6333
        JWT_SECRET_KEY: test-secret-key
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella